development:
  adapter: postgresql
  host: localhost
  database: tellajoke_development
  username: tellajoke
  password: tellajoke
  pool: 5
  schema_search_path: public
  encoding: utf8
  timeout: 5000
  template: template0

test:
  adapter: postgresql
  host: localhost
  database: tellajoke_test
  username: tellajoke
  password: tellajoke
  pool: 5
  schema_search_path: public
  encoding: utf8
  timeout: 5000
  template: template0

